apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgAh78Thv45mgMnFgKBIhfJdnEp0huRCKuh9Y3bVcvkbyQ/7bUCQ1yOiHaIQzkVaLG138rTZOAlkhHdqvqe8W5CePsx8an5vgTjnmU7exW1FLHtTn828jIYRovp7RL6FqG3xGb3wh2F5wq0idxOgAvWYq4f0llaQ1i7Rq5BOHvkSOb1ElvtX0+NIfVDrhV8bXQaYkY+gsriIcwkY1fn4/ZlAHwSka9bCK8szFCEmmFn+qYIO0QaNASdkxRC05TgeDAKyazaB43Ths1zBe2udsD6xXgUeeOWyAgGb/5Jkv3egDlyelBOEOzlPMfPfUokHAHfOcPI1n6x2+VJvJpA9c1euZ1gKLNi5ZTARXV692rZhaRIaIqlZk6uTqPurpq6AYJSkLqzGzpsvl3PIRi7gXGCN6//uSw5Fowx3ioTX2NV+Bq4J9HzH5B+qCLu+D6PVHNc2XuJOyt5H+gpxj8PXJRUfs9uFfnqMJT4F4ktlLIDqJfcaxbbhZxwHM1h+m7gmEl/yt8bxK1dX1w+AW0bBtm7baXDpm1amd7IN4HOmeccCrWyOH1GB2wsqutLVeaezQt6BQrdfeQNlFauWs6l2plwvmShJhaKJbmOWVsgnhV+ftXJFVdpgl7nKnB30kxD6HysQU9+6xQIzdy7Z0eyJLHB9g4kYHgX8VGDcjdEy9MBwn0EaRHj7NlH9CnjpbcfoQOOgK6WSV1gTUwLyHqQ67CO1Pq5Rzq3XRbKA7xcAO4yjEHExfYWrxk0/X765+zVRPU1apxxDjqiPZGNV+0MuIdDKxrMMt9iKYb6EmetOyNFOQPYS9cfRKJFT/7VTOOsV1MEa7waUwDt5A8+iD0aXL+cKc8B9LwPa3BW6gD3YdvMEicuebTDIAH3Xc4CAwmkImwqSQ4LxjqLwXCwUFpneZ7gp+rfBO+nSWbJz3mls34EPpT7xxdb322FjMUX8YCEYeiKkKoW+ShC1WcC4xM3uTeOsATL07GcouZCLfAIwFsz+8cpg8NSLQrKDl1fgWP5H1UmRxq3hKAUKojFmj2BeqwCWIJzgzvbnPNXW8YhPZJ+d61bqfXb4MA/iL5cXXToms5hUuYyV2mCkNcvMFpMNmKEYAk+ZFd38MlmGm48KzufE1dD1zPwbeJhoi2Xry0Bcv1FgFjrBfMBgzmKTDqpCO84lb4YJ3CI8lgvgU9LCSIhrGJ5uDPM9VlxwtAchdLSXeSJ7cnuFTQdJUZsBVfOJKQ65vXEBwDHPwYQvx6wM4XDLfx2Q5oNwkTO6+VsSsS6fUSZ3uMqfGdFUo70X45lT1BnPQLL5Ql30M61smfhzGMABCjA2pU2dr2g+Zkg+DWyj12XM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

